config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :proposals

  ################ ADMIN ZONE #############

  namespace :admin do
  	resources :users
  	resources :possibles
    resources :proposals
  end

  end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/possible.rb
class Possible < ApplicationRecord
	has_many :proposal_possibles
	has_many :proposals, through: :proposal_possibles
end

app/models/proposal.rb
class Proposal < ApplicationRecord

	validates :accepted, presence: true
	validates :comment, presence: true

	belongs_to :user
	

	has_many :proposal_possibles
	has_many :possibles, through: :proposal_possibles


end

app/models/proposal_possible.rb
class ProposalPossible < ApplicationRecord
	belongs_to :proposal
	belongs_to :possible
end

app/models/user.rb
class User < ApplicationRecord
	has_one :proposal

	validates :name, presence: true, 
				uniqueness: true
	validates :email, presence: true
end

app/controllers/admin/home_controller.rb
class Admin::HomeController < ApplicationController
	def index
		
	end
end

app/controllers/admin/possibles_controller.rb
class Admin::PossiblesController < ApplicationController
  before_action :set_possible, only: [:show, :edit, :update, :destroy]




  def index
    @possibles = Possible.all
  end

  def show
  end


  def new
    @possible = Possible.new
  end


  def edit
  end


  def create
    @possible = Possible.new(possible_params)

    respond_to do |format|
      if @possible.save
        format.html { redirect_to admin_possibles_path, notice: 'Possible was successfully created.' }
        format.json { render :show, status: :created, location: @possible }
      else
        format.html { render :new }
        format.json { render json: @possible.errors, status: :unprocessable_entity }
      end
    end
  end


  def update
    respond_to do |format|
      if @possible.update(possible_params)
        format.html { redirect_to admin_possible_path(@possible), notice: 'Possible was successfully updated.' }

      else
        format.html { render :edit }
        format.json { render json: @possible.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy
    @possible.destroy
    respond_to do |format|
      format.html { redirect_to admin_possibles_path, notice: 'Possible was successfully destroyed.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_possible
      @possible = Possible.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def possible_params
      params.require(:possible).permit(:date)
    end
end

app/controllers/admin/proposals_controller.rb
class Admin::ProposalsController < ApplicationController
  before_action :set_proposal, only: [:show, :edit, :update, :destroy]

  def index
    @proposals = Proposal.all


  end

  def show
    @proposal = Proposal.find(params[:id])
  end

  def destroy
    @proposal.destroy
    respond_to do |format|
      format.html { redirect_to proposals_url, notice: 'Proposal was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_proposal
    @proposal = Proposal.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def proposal_params
    params.require(:proposal).permit(:accepted, :comment, possible_ids:[])
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]



  def index
    @users = User.all
  end

  def show
  end


  def new
    @user = User.new
  end

 
  def edit
  end


  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save

        format.html { redirect_to admin_users_path, notice: 'User was successfully created.' }

        UserMailer.with(user: @user).confirmation_email.deliver_now

      else
        format.html { render 'admin/users/new' }

      end
    end
  end


  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to admin_users_path, notice: 'User was successfully updated.' }

      else
        format.html { render :edit }

      end
    end
  end


  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to admin_users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/possibles_controller.rb
class PossiblesController < ApplicationController

end

app/controllers/proposals_controller.rb
class ProposalsController < ApplicationController
  before_action :set_proposal, only: [:show, :edit, :update, :destroy]



  def index
    @proposals = Proposal.all
  end



 
  def new
    @proposal = Proposal.new
    @possibles = Possible.all
  end


  def edit
  end




  def create
    @proposal = Proposal.new(proposal_params)

    @proposal.user_id = session[:user_id]

    respond_to do |format|
      if @proposal.save
        format.html { redirect_to @proposal, notice: 'Muchas gracias por participar. Puedes revisar tu propuesta:' }

        flash[:notice] = "Tu propuesta de fechas se ha guardado, gracias por participar."

      else
        format.html { render :new }

      end
    end
  end

 
  def update
    respond_to do |format|
      if @proposal.update(proposal_params)
        format.html { redirect_to @proposal, notice: 'Tu propuesta de fecha ha sido actualizada.' }

      else
        format.html { render :edit }

      end
    end
  end

  def show
    @proposal = Proposal.find(params[:id])
  end


  def destroy
    @proposal.destroy
    respond_to do |format|
      format.html { redirect_to proposals_url, notice: 'Proposal was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_proposal
      @proposal = Proposal.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def proposal_params
      params.require(:proposal).permit(:accepted, :comment, possible_ids:[])
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new

	end



	def create
		user = User.find_by(email: params[:email].downcase)
		if user
			session[:user_id] = user.id
			flash[:notice] = "Ya estás loguead@!"

			proposal = Proposal.find_by_user_id(user.id)

			if proposal
				flash[:alert]= "Ya has realizado una propuesta de fecha y no puedes hacer más"
				redirect_to root_path
			else

				redirect_to new_proposal_path
			end


		else
			flash[:alert]= "No estás dad@ de alta o has escrito mal el email"
			redirect_to login_path
		end 


	end


	def destroy

	end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
      @possibles = Possible.all

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/possibles_helper.rb
module PossiblesHelper
end

app/helpers/proposals_helper.rb
module ProposalsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/possibles/_edit_form.html.erb
<%= form_for(@possible, url: admin_possible_path(@possible), html:{}) do |form| %>
  <% if possible.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(possible.errors.count, "error") %> prohibited this possible from being saved:</h2>

      <ul>
      <% possible.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= form.label :date %>
    <%= form.date_select :date %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/possibles/_new_form.html.erb
<%= form_for(@possible, url: admin_possibles_path, html:{}) do |form| %>
  <% if possible.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(possible.errors.count, "error") %> prohibited this possible from being saved:</h2>

      <ul>
      <% possible.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= form.label :date %>
    <%= form.date_select :date %>

  </div>



  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/possibles/edit.html.erb
<h1>Editing Possible</h1>

<%= render 'admin/possibles/edit_form', possible: @possible %>

<%= link_to 'Show', admin_possible_path(@possible) %> |
<%= link_to 'Back', admin_possibles_path %>

app/views/admin/possibles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Possibles</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @possibles.each do |possible| %>
      <tr>
        <td><%= possible.date %></td>
        <td><%= link_to 'Show', admin_possible_path(possible) %></td>
        <td><%= link_to 'Edit', edit_admin_possible_path(possible) %></td>
        <td><%= link_to 'Destroy', admin_possible_path(possible), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Possible', new_admin_possible_path %>

app/views/admin/possibles/new.html.erb
<h3 class= "alert alert-info">Introduce una nueva fecha para la posible quedada</h3>

<div class="well">
  <%= render 'admin/possibles/new_form', possible: @possible %>
</div>


<button type="button" class="btn btn-primary">
  <%= link_to 'Back', admin_possibles_path %>
</button>

app/views/admin/possibles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Fechas posible:</strong>
  <%= @possible.date %>
</p>



<%= link_to 'Edit', edit_admin_possible_path(@possible) %> |
<%= link_to 'Back', admin_possibles_path %>

app/views/admin/proposals/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Fechas propuestas</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @proposals.each do |proposal| %>
      <tr>
        <td><%= proposal.user.name %></td>
        <td><%= proposal.accepted %></td>
        <td><%= proposal.comment %></td>
        <td>
          <% proposal.possibles.each do |possible| %>
            <li><%= possible.date %></li>
          <% end %>
        </td>
        <td><%= link_to 'Show', admin_proposal_path(proposal) %></td>
        <td><%= link_to 'Edit', edit_proposal_path(proposal) %></td>
        <td><%= link_to 'Destroy', proposal_path(proposal), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/admin/proposals/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Detalle de la propuesta</h1>

<p>
  <strong>Accepted:</strong>
  <%= @proposal.accepted %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @proposal.comment %>
</p>


<p>
  <strong>Fechas preferidas:</strong>
	<% @proposal.possibles.each do |possible| %>
     	<li><%= possible.date %></li>
 	<% end %>
 </p>




<%= link_to 'Back', admin_proposals_path %>

app/views/admin/users/_edit_form.html.erb
<%= form_for(@user, url: admin_user_path(@user), html:{}) do |form| %>


  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>



  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/users/_new_form.html.erb
<%= form_for(@user, url: admin_users_path, html:{}) do |form| %>


  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>



  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.email_field :email,placeholder: "Email", autofocus: true %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'admin/users/edit_form', user: @user %>

<%= link_to 'Show', admin_user_path(@user) %> |
<%= link_to 'Back', admin_users_path %>

app/views/admin/users/index.html.erb
<h1>Users</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', admin_user_path(user) %></td>
        <td><%= link_to 'Edit', edit_admin_user_path(user) %></td>
        <td><%= link_to 'Destroy', admin_user_path(user), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_admin_user_path %>

app/views/admin/users/new.html.erb
<h1>New User</h1>




<%= render 'admin/users/new_form', user: @user %>

<%= link_to 'Back', admin_users_path %>

app/views/admin/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_admin_user_path(@user) %> |
<%= link_to 'Back', admin_users_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>QuedAPPmos?</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>


  </head>

  <body>

<div class="row">
  <% if notice.present? %>
    <div class="alert alert-success alert-dismissable col-sm-9">

      <strong><%= t('common.info') %></strong>
      <%= notice.html_safe %>
      <button class="close" aria-hidden="true" data-dismiss="alert" type="button">×</button>
    </div>
  <% end %>
  <% if alert.present? %>
    <div class="alert alert-danger alert-dismissable col-sm-9">

      <strong><%= t('common.danger') %></strong>
      <%= alert.html_safe %>
      <button class="close" aria-hidden="true" data-dismiss="alert" type="button">×</button>
    </div>
  <% end %>
</div>


  <%= yield %>



  </body>
</html>

app/views/proposals/_form.html.erb
  <%= form_with(model: proposal, local: true, class: "form-group") do |form| %>
    <% if proposal.errors.any? %>
      <div>
          <div class="panel panel-danger">
            <div class="panel-heading">
              <h2 class="panel-title"><%= pluralize(proposal.errors.count, "error") %> impide que tu propuesta sea guardada:</h2>
                <div class="panel-body">
                  <ul>
                    <% proposal.errors.full_messages.each do |message| %>
                      <li><%= message %></li>
                    <% end %>
                  </ul>
                </div>
            </div>
        </div>
      </div>
    <% end %>


    <div class="center field row form-group">
      <div class="row"><h4>Selecciona la siguiente casilla si aceptas quedar para un plan sorpresa:</h4></div>
      <div class="row"><%= form.label :acepto %></div>
      <div class="row"><%= form.check_box :accepted %></div>
    </div>
    <hr>
    <br>

    <div class="row"><p>Selecciona una o varias de las siguientes fechas posibles:</p></div>

    <div class="form-group">

      <div class="row">
        <div class="col-sm-2"></div>
        <div class="col-sm-8 alert alert-warning">
          <%= form.collection_check_boxes :possible_ids, Possible.all, :id, :date do |possible| %>
            <% possible.label(class: "checkbox-inline input_checkbox") {possible.check_box(class:"checkbox") + possible.text} %>
          <% end %>
        </div>
        <div class="col-sm-2"></div>
      </div>
    </div>
    <hr>

    <div class="field form-group col-sm-12 row">
      <div class="col-sm-3"></div>
        <div class="col-sm-6">
          <%= form.text_area :comment, class: "form-control", placeholder: "Deja aquí tus comentarios", rows:3 %>
        </div>
      <div class="col-sm-3"></div>

    </div>
    <br>
    <br>



    <div class="actions">
      <%= form.submit class: "btn btn-success btn-lg", value:"Enviar" %>
    </div>
  <% end %>

</div>

app/views/proposals/edit.html.erb
<div class="jumbotron jumboformproposal center">

  <%= render 'form', proposal: @proposal %>

  <%= link_to 'Mostrar', @proposal %> |
  <%= link_to 'Inicio', root_path %>
</div>

app/views/proposals/new.html.erb
<div class="jumbotron jumboformproposal center">

  <div class="alert alert-success">
    <h3 class="title2">Rellena el siguiente formulario e indícanos tus preferencias:</h3>
  </div>
  <%= render 'form', proposal: @proposal %>

  <%= link_to 'Inicio', root_path %>
</div>

app/views/proposals/show.html.erb
<div class="well col-sm-3">
	<p id="notice"><%= notice %></p>

	<p>
		<strong>Aceptas:</strong>
		<%= @proposal.accepted %>
	</p>

	<p>
		<strong>Fechas seleccionadas:</strong>
		<% @proposal.possibles.each do |possible| %>
		<li><%= possible.date %></li>
	<% end %>
	</p>

	<p>
		<strong>Comentario:</strong>
		<%= @proposal.comment %>
	</p>

	<%= link_to 'Editar', edit_proposal_path(@proposal) %> |
	<%= link_to 'Inicio', root_path %>

</div>

app/views/shared/_possibles.html.erb
<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @possibles.each do |possible| %>
    <tr>
      <td>
      	<ul><li><%= possible.date %></li></ul>
      </td>
    </tr> 
    <% end %>
  </tbody>
</table>

app/views/welcome/index.html.erb
		<div class="center jumbotron jumboindex col-sm-9">

				<div class="title">
					<h1>Qued<i class="app">APP</i>mos?</h1>
				</div>
				<br>

				<div class="homeimage"><%= image_tag '' %></div>

		  		<br>

				<div class="row">
					<div class="well col-sm-12">
						<p><h3 class="title2">¡Bienvenidos a la app para organizar una quedada inolvidable!</h3></p>
						<br>

						<div class="row col-sm-12 center">

							<!-- Button trigger modal -->
							<button type="button" class="btn btn-circle center information" data-toggle="modal" data-target="#exampleModal">
									i
							</button>

							<!-- Modal -->
							<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
								<div class="modal-dialog" role="document">
									<div class="modal-content">
										<div class="modal-header">
											<h5 class="modal-title" id="exampleModalLabel">Instrucciones:</h5>
											<button type="button" class="close" data-dismiss="modal" aria-label="Close">
												<span aria-hidden="true">&times;</span>
											</button>
										</div>
										<div class="modal-body">
										</div>
										<ol>
											<li><h5>Regístrate escribiendo a: <a href=”mailto:fernando.mencia@string.projects.com”>fernando.mencia@string.projects.com</a></h5></li>
											<li><h5>Te llegará un correo confirmando que ya estás registrado.</h5></li>
											<li><h5>Cuando estés registrado loguéate y contesta al formulario.</h5></li>
											<li><h5>En breve recibirás otro correo con la fecha definitiva de la actividad.</h5></li>
											<br>
										</ol>
									</div>
										</div>
										<div class="modal-footer">
											<button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>

										</div>
									</div>
								</div>
					</div>
					<br>

						<%= link_to 'login', login_path,class:"btn btn-default btn-lg btn-xlarge login" %>
					</div>



		</div>